# -*- coding: utf-8 -*-
"""facerecognition2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2tGzjGKpNh7GfNQE7zBeo1S5XbdTXHO
"""
import cv2
import mediapipe as mp

print("Python script berhasil dijalankan!")

mp_face = mp.solutions.face_detection
detector = mp_face.FaceDetection(min_detection_confidence=0.7)

print("Face Detection siap digunakan.")


# import cv2
# import mediapipe as mp

# mp_face = mp.solutions.face_detection
# mp_draw = mp.solutions.drawing_utils

# cap = cv2.VideoCapture(0)
# detector = mp_face.FaceDetection(min_detection_confidence=0.7)

# while True:
#     ret, frame = cap.read()
#     if not ret:
#         break

#     rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
#     result = detector.process(rgb)

#     if result.detections:
#         for detect in result.detections:
#             mp_draw.draw_detection(frame, detect)

#     cv2.imshow('Face Detection', frame)
#     if cv2.waitKey(1) & 0xFF == 27:  # Tekan ESC untuk keluar
#         break

# cap.release()
# cv2.destroyAllWindows()

# import os

# cam = cv2.VideoCapture(0)
# name = input("Masukkan nama: ")

# path = f"dataset/{name}"
# os.makedirs(path, exist_ok=True)

# count = 0
# while True:
#     ret, frame = cam.read()
#     if not ret:
#         break

#     cv2.imshow("Ambil Gambar (Tekan SPACE untuk Capture, ESC untuk Keluar)", frame)
#     k = cv2.waitKey(1)
#     if k % 256 == 27:  # ESC
#         break
#     elif k % 256 == 32:  # SPACE
#         img_name = f"{path}/{count}.jpg"
#         cv2.imwrite(img_name, frame)
#         print(f"{img_name} disimpan!")
#         count += 1

# cam.release()
# cv2.destroyAllWindows()

# import csv
# from datetime import datetime

# cap = cv2.VideoCapture(0)
# detector = mp_face.FaceDetection(min_detection_confidence=0.7)

# with open('absensi.csv', 'a', newline='') as f:
#     writer = csv.writer(f)

#     while True:
#         ret, frame = cap.read()
#         if not ret:
#             break

#         rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
#         result = detector.process(rgb)

#         if result.detections:
#             for detect in result.detections:
#                 mp_draw.draw_detection(frame, detect)
#                 name = "Terdeteksi"  # nanti diganti dengan hasil pengenalan
#                 writer.writerow([name, datetime.now().strftime("%Y-%m-%d %H:%M:%S")])
#                 print("Absensi tercatat")

#         cv2.imshow('Absensi Wajah', frame)
#         if cv2.waitKey(1) & 0xFF == 27:
#             break

# cap.release()
# cv2.destroyAllWindows()